# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Store.s' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'firebase/Core'
  pod 'firebase/Auth'


end
